version: "3.9"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
      - "8055:8080"
    environment:
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DEBUG=1
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=fake-access-key
      - AWS_SECRET_ACCESS_KEY=fake-secret-key
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/local/localstack:/docker-entrypoint-initaws.d"